version: '2'

services:
  fpm:
    build:
      context: .
      dockerfile: infrastructure/cli/Dockerfile
    image: realpage/regular-updates:cli
    env_file: .env
    volumes:
      - ./:/var/www/html